[BUGFIX] iwlwifi: fix chrome compilation with 5.11
One cfg80211 patch wasn't sent upstream, and because of that
cfg80211.h doesn't include uapi/linux/rfkill.h.

This patch is:
	cfg80211: allow to specifying a reason for hw_rfkill

This caused this:
 drivers/net/wireless/iwl7000/iwlwifi/mvm/ops.c:829:7: error: ‘RFKILL_HARD_BLOCK_NOT_OWNER’ undeclared (first use in this function)
        RFKILL_HARD_BLOCK_NOT_OWNER);
        ^

Include uapi/linux/rfkill.h from mvm/ops.c to fix this
which is the right thing to do anyway since mvm/ops.c
needs RFKILL_HARD_BLOCK_NOT_OWNER.

The cfg80211 patch missing also caused this:

 drivers/net/wireless/iwl7000/iwlwifi/mvm/ops.c:827:2: error: implicit declaration of function ‘wiphy_rfkill_set_hw_state_reason’ [-Werror=implicit-function-declaration]
   wiphy_rfkill_set_hw_state_reason(mvm->hw->wiphy,

Make the inline in iwl-chrome.h unconditional so that
it'll be available even for 5.11.
When the cfg80211 patch will hit upstream, we'll need
to remove this.

type=bugfix
fixes=Ibf66e3e248d549166d1eb340c60ee5b2a1dada78
ticket=none

Change-Id: I9faeb710b59690d3a46da6792c48f8d3a2daa8eb
Signed-off-by: Emmanuel Grumbach <emmanuel.grumbach@intel.com>
Reviewed-on: https://git-amr-3.devtools.intel.com/gerrit/292002
Tested-by: ec ger unix iil jenkins <EC.GER.UNIX.IIL.JENKINS@INTEL.COM>
Reviewed-by: Luciano Coelho <luciano.coelho@intel.com>
x-iwlwifi-stack-dev: 06b8160f933fb9ec5c8b7f451a6a96c0ed7c8a1f