[BUGFIX] iwlwifi: mvm: fix compilation with IWLMVM_AX_SOFTAP_TESTMODE
If IWLMVM_AX_SOFTAP_TESTMODE is set but IWLWIFI_DEVICE_TESTMODE is
not, compilation breaks:

/home/luca/iwlwifi/stack-dev/drivers/net/wireless/intel/iwlwifi/mvm/mac80211.c:5055:21: error: 'iwl_mvm_ax_softap_testmode_sta_add_debugfs' undeclared here (not in a function)
  .sta_add_debugfs = iwl_mvm_ax_softap_testmode_sta_add_debugfs,
                     ^
scripts/Makefile.build:258: recipe for target '/home/luca/iwlwifi/stack-dev/drivers/net/wireless/intel/iwlwifi/mvm/mac80211.o' failed

This is because we erroneously check for IWLWIFI_DEVICE_TESTMODE
before defining the function in mvm.h.

type=bugfix
ticket=none
fixes=Id3d68542f03a71c9415d149b0dad6f8e9ab2a052

Change-Id: I6778fd1e15509a98d7aa9ea779f6d156f278b34b
Signed-off-by: Luca Coelho <luciano.coelho@intel.com>
Reviewed-on: https://git-amr-3.devtools.intel.com/gerrit/132846
Tested-by: ec ger unix iil jenkins <EC.GER.UNIX.IIL.JENKINS@INTEL.COM>
Reviewed-by: Afek, JonathanX <jonathanx.afek@intel.com>
x-iwlwifi-stack-dev: 607085111b87af2ba7ad2c3567b8d291534c78cc