[BUGFIX] iwlwifi: dbg_ini: fix structure packing
The iwl_fw_ini_error_dump_range structure has conflicting alignment
requirements for the inner union and the outer struct:

In file included from drivers/net/wireless/intel/iwlwifi/fw/dbg.c:9:
drivers/net/wireless/intel/iwlwifi/fw/error-dump.h:312:2: error: field  within 'struct iwl_fw_ini_error_dump_range' is less aligned than 'union iwl_fw_ini_error_dump_range::(anonymous at drivers/net/wireless/intel/iwlwifi/fw/error-dump.h:312:2)' and is usually due to 'struct iwl_fw_ini_error_dump_range' being packed, which can lead to unaligned accesses [-Werror,-Wunaligned-access]
        union {

As the original intention was apparently to make the entire structure
unaligned, mark the innermost members the same way so the union
becomes packed as well.

type=bugfix
ticket=none
fixes=I9d148dd6b6bcae848b70ffd39acf5903a8a251e8

Fixes: 973193554cae ("iwlwifi: dbg_ini: dump headers cleanup")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Gregory Greenman <gregory.greenman@intel.com>
Change-Id: I7f2c715d9ad6b04cd17158e43b7124cd5abf6ad6
Reviewed-on: https://gerritwcs.ir.intel.com/c/iwlwifi-stack-dev/+/69125
tested: iil_jenkins <EC.GER.UNIX.IIL.JENKINS@INTEL.COM>
Tested-by: iil_jenkins <EC.GER.UNIX.IIL.JENKINS@INTEL.COM>
Reviewed-by: Berg, Johannes <johannes.berg@intel.com>
x-iwlwifi-stack-dev: 78a7b11c1ed05d322469afeb86c6381ca2477b1b