[BUGFIX] iwlwifi: pcie: fix compilation with IWLWIFI_PLATFORM_DATA [NOUPSTREAM]
I broke compilation when IWLWIFI_PLATFORM_DATA is enabled:

/home/emmanuel/Work/iwlwifi-stack-dev/drivers/net/wireless/intel/iwlwifi/pcie/trans.c:1178:20: error: implicit declaration of function ‘iwl_trans_pcie_power_device_off’ [-Werror=implicit-function-declaration]
  if (low_power && !iwl_trans_pcie_power_device_off(trans_pcie)) {
                    ^
type=bugfix
bug=not-tracked
fixes=I68148ae7249772535a55e7722fd16200dd7bb2f8

Change-Id: I29a63b8845cca676d269856fff902b58fdbbdf92
Signed-off-by: Emmanuel Grumbach <emmanuel.grumbach@intel.com>
Reviewed-on: https://git-amr-3.devtools.intel.com/gerrit/19067
Tested-by: ec ger unix iil jenkins <EC.GER.UNIX.IIL.JENKINS@INTEL.COM>
x-iwlwifi-stack-dev: 3b857f93b34c7a4fe26c2dcdf3bf765b781c52b5