[BUGFIX] iwlwifi: mvm: fix SAR compilation without CONFIG_ACPI
Builds with CONFIG_ACPI disabled fail as follows.

drivers/net/wireless/iwl7000/iwlwifi/mvm/fw.c: In function 'iwl_mvm_sar_init':
drivers/net/wireless/iwl7000/iwlwifi/mvm/fw.c:1598:9: error:
	'struct iwl_mvm' has no member named 'sar_chain_a_profile'
drivers/net/wireless/iwl7000/iwlwifi/mvm/fw.c:1598:37: error:
	'struct iwl_mvm' has no member named 'sar_chain_b_profile'

because the structure members are only available with CONFIG_ACPI.

type=bugfix
fixes=I93afa765c7f2d7caf5e4f1312fb7c47eb45781d8
ticket=none

Change-Id: I1fdf24ab1434f4e70b1de3764598b9076c83f5ce
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Signed-off-by: Luca Coelho <luciano.coelho@intel.com>
Reviewed-on: https://git-amr-3.devtools.intel.com/gerrit/129375
Reviewed-by: ec ger unix iil jenkins <EC.GER.UNIX.IIL.JENKINS@INTEL.COM>
Tested-by: ec ger unix iil jenkins <EC.GER.UNIX.IIL.JENKINS@INTEL.COM>
Reviewed-by: Dreyfuss, Haim <haim.dreyfuss@intel.com>
x-iwlwifi-stack-dev: ab43749751e1f994b1712758312ac8c542fe0693