iwlwifi: sdio: fix compilation error
Commit a754ce4 ("iwlwifi: sdio: support dump data") introduced
the following compilation error:

drivers/net/wireless/iwlwifi/trans_slave/sdio_trans.c: In function 'iwl_trans_sdio_dump_data':
drivers/net/wireless/iwlwifi/trans_slave/sdio_trans.c:2461:2: error: implicit declaration of function 'vzalloc' [-Werror=implicit-function-declaration]
drivers/net/wireless/iwlwifi/trans_slave/sdio_trans.c:2461:12: warning: assignment makes pointer from integer without a cast [enabled by default]

Add the missing vmalloc.h include.

Change-Id: I9b9aaf04abd9e3498b37f8bf4dcca0858a0c2893
Signed-off-by: Eliad Peller <eliadx.peller@intel.com>
Reviewed-on: https://gerrit.rds.intel.com/r/48639
Reviewed-by: Johannes Berg <johannes.berg@intel.com>
Tested-by: Johannes Berg <johannes.berg@intel.com>
x-iwlwifi-stack-dev: 5341317404ebb2030414dd4ec6b427230fc7562b